# Generated by Django 5.2 on 2025-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(blank=True, max_length=200, null=True)),
                ('extensao', models.CharField(blank=True, max_length=5, null=True)),
                ('tamanho', models.FloatField(blank=True, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_arquivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(blank=True, null=True)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_autorizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChCategoriaDoChamado',
            fields=[
                ('pk', models.CompositePrimaryKey('id_chamado', 'id_subcategoria', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ch_categoria_do_chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.IntegerField(blank=True, null=True)),
                ('patrimonio', models.IntegerField(blank=True, null=True)),
                ('data_inicio_suporte', models.DateTimeField(blank=True, null=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('suporte', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_interacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChServicosChamado',
            fields=[
                ('pk', models.CompositePrimaryKey('id_servicos', 'id_chamado', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_servicos_chamado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ch_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('autorizacao', models.IntegerField(blank=True, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_subcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuGrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usu_grupo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('suporte', models.IntegerField(blank=True, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usu_setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('deletado', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usu_unidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_exibicao', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email_institucional', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('deletado', models.BooleanField()),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usu_usuario',
                'managed': False,
            },
        ),
    ]
